-- begin; --uncomment if running with rollback

drop table if exists public.assigned_learning_resource;
drop table if exists public.assigned_compliance_resource;
drop table if exists public.user;
drop table if exists public.user_role;
drop table if exists public.learning_resource;
drop table if exists public.learning_resource_type;
drop table if exists public.compliance_resource;
drop table if exists public.resource_status;

create table
  public.learning_resource_type (
    id smallint generated always as identity not null,
    name character varying not null,
    description character varying null,
    constraint learning_type_pkey primary key (id),
    constraint learning_resource_type_id_key unique (id)
  ) tablespace pg_default;

create table
  public.learning_resource (
    id smallint generated always as identity not null,
    type_id smallint not null,
    name character varying not null,
    url character varying null,
    description character varying null,
    deadline_at timestamp with time zone null,
    is_mandatory boolean null,
    is_active boolean null default true,
    created_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    constraint learning_resource_pkey primary key (id),
    constraint learning_resource_id_key unique (id),
    constraint learning_resource_type_id_fkey foreign key (type_id) references learning_resource_type (id)
  ) tablespace pg_default;

create table public.resource_status (
  id smallint generated always as identity not null,
  name character varying not null,
  description character varying null,
  constraint resource_status_pkey primary key (id),
  constraint resource_status_name_key unique (name)
) tablespace pg_default;

create table
  public.user_role (
    id smallint generated always as identity not null,
    name character varying not null,
    description character varying not null,
    constraint user_role_pkey primary key (id),
    constraint user_role_id_key unique (id)
  ) tablespace pg_default;

create table
  public.user (
    id integer generated by default as identity not null,
    auth_id uuid not null default auth.uid (),
    role_id smallint not null default '1'::smallint,
    first_name character varying not null,
    last_name character varying null,
    email character varying not null,
    is_active boolean null default true,
    constraint user_pkey primary key (id),
    constraint user_authId_key unique (auth_id),
    constraint user_email_key unique (email),
    constraint user_id_key unique (id),
    constraint user_auth_id_fkey foreign KEY (auth_id) references auth.users (id) on update CASCADE on delete CASCADE,
    constraint user_role_id_fkey foreign KEY (role_id) references user_role (id)
  ) TABLESPACE pg_default;

create table
  public.assigned_learning_resource (
    id bigint generated always as identity not null,
    user_id integer not null,
    resource_id smallint not null,
    status_id smallint not null default '1'::smallint,
    started_at timestamp with time zone null,
    completed_at timestamp with time zone null,
    modified_at timestamp with time zone null,
    created_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    constraint assigned_learning_resource_pkey primary key (id),
    constraint assigned_learning_resource_id_key unique (id),
    constraint assigned_learning_resource_resource_id_fkey foreign key (resource_id) references learning_resource (id),
    constraint assigned_learning_resource_status_id_fkey foreign key (status_id) references resource_status (id),
    constraint assigned_learning_resource_user_id_fkey foreign key (user_id) references "user" (id) on delete CASCADE
  ) tablespace pg_default;

create table public.compliance_resource (
  id smallint generated by default as identity not null,
  name character varying not null,
  description character varying null,
  url character varying null,
  is_active boolean null default true,
  deadline_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  constraint compliance_resource_pkey primary key (id),
  constraint compliance_resource_id_key unique (id)
) TABLESPACE pg_default;

create table public.assigned_compliance_resource (
  id bigint generated always as identity not null,
  user_id integer not null,
  resource_id smallint not null,
  status_id smallint not null default '1'::smallint,
  started_at timestamp with time zone null,
  completed_at timestamp with time zone null,
  modified_at timestamp with time zone null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  constraint assigned_compliance_resource_pkey primary key (id),
  constraint assigned_compliance_resource_resource_id_fkey foreign KEY (resource_id) references compliance_resource (id),
  constraint assigned_compliance_resource_status_id_fkey foreign KEY (status_id) references resource_status (id),
  constraint assigned_compliance_resource_user_id_fkey foreign KEY (user_id) references "user" (id) on delete CASCADE
) TABLESPACE pg_default;

alter sequence public.assigned_learning_resource_id_seq restart with 1;
alter sequence public.assigned_compliance_resource_id_seq restart with 1;
alter sequence public.user_id_seq restart with 1;
alter sequence public.user_role_id_seq restart with 1;
alter sequence public.learning_resource_id_seq restart with 1;
alter sequence public.learning_resource_type_id_seq restart with 1;
alter sequence public.compliance_resource_id_seq restart with 1;
alter sequence public.resource_status_id_seq restart with 1;

-- rollback; --uncomment if running with rollback