export * from "./skeleton"
export { default as SkeletonAssignedRequirements } from "./skeleton-assigned-requirements"
export { default as SkeletonAssignedTrainings } from "./skeleton-assigned-trainings"
export { default as SkeletonManageUsers } from "./skeleton-manage-users"
export { default as SkeletonManageRequirements } from "./skeleton-manage-requirements"
export { default as SkeletonManageTrainings } from "./skeleton-manage-trainings"
