export { default as AddTraining } from "./components/AddTraining"
export { default as AssignedTrainings } from "./components/AssignedTrainings"
export { default as DisableTraining } from "./components/DisableTraining"
export { default as TrainingsList } from "./components/TrainingsList"
export { default as UpdateTraining } from "./components/UpdateTraining"
export { default as AssignedTrainingUsers } from "./components/AssignedTrainingUsers"
